services:
  stolz-learn.core.postgres:
    image: postgres:16
    container_name: 'stolz-learn.core.postgres'
    command:
      - "postgres"
      - "-c"
      - "TimeZone=Europe/Vienna"
    restart: unless-stopped
    ports:
      - "127.0.0.1:5867:5432"
    environment:
      POSTGRES_USER: "stolz_learn_core_app"
      POSTGRES_DB: "stolz_learn_core"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_PASSWORD: "anAwesomePassword"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg-data/core:/var/lib/postgresql/data